In [1]:
import os
import sys

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.append(project_root)

In [2]:
import torch
import torch.nn as nn
import numpy as np

print("PyTorch Version :", torch.__version__)
print("CUDA Available :", torch.cuda.is_available())

PyTorch Version : 2.13.0+cpu
CUDA Available : False


In [3]:
from src.config import *

print("Available Price Levels")
print(PRICE_LEVELS)

print("\nTotal Price Actions :", len(PRICE_LEVELS))

Available Price Levels
[80, 100, 120, 140, 160]

Total Price Actions : 5


In [4]:
from src.environment import HotelPricingEnv

env = HotelPricingEnv()
state, info = env.reset()

print("Initial Environment State")
print(state)

Initial Environment State
[50 30]


In [5]:
from src.dqn_model import DQN

In [6]:
state_size = 2

action_size = len(PRICE_LEVELS)

model = DQN(state_size,action_size)

print(model)

DQN(
  (network): Sequential(
    (0): Linear(in_features=2, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=32, bias=True)
    (5): ReLU()
    (6): Linear(in_features=32, out_features=5, bias=True)
  )
)


In [7]:
sample_state = torch.FloatTensor([[50, 30]])

output = model(sample_state)

print("Predicted Q-Values")

print(output)

Predicted Q-Values
tensor([[-1.7710,  1.1784,  0.0751,  4.9830, -1.9014]],
       grad_fn=<AddmmBackward0>)


In [8]:
states = torch.FloatTensor([
    [50, 30],
    [40, 20],
    [25, 15],
    [10, 5]
])

predictions = model(states)

print("Predicted Q-Values for Batch States")
print(predictions)

Predicted Q-Values for Batch States
tensor([[-1.7710,  1.1784,  0.0751,  4.9830, -1.9014],
        [-1.2899,  0.8790,  0.0382,  3.5047, -1.4001],
        [-0.9276,  0.6904, -0.0162,  2.4956, -0.8472],
        [-0.3956,  0.3637, -0.0776,  0.8780, -0.1909]],
       grad_fn=<AddmmBackward0>)


In [9]:
print("Batch Predictions\n")

for i in range(len(states)):

    print(f"State {i+1}: {states[i].tolist()}")

    print("Q-Values:")

    print(predictions[i].detach().numpy())

    print("-" * 50)

Batch Predictions

State 1: [50.0, 30.0]
Q-Values:
[-1.7710029   1.1783637   0.07512218  4.9829664  -1.9014454 ]
--------------------------------------------------
State 2: [40.0, 20.0]
Q-Values:
[-1.2898895   0.87902975  0.03824717  3.5046935  -1.4000508 ]
--------------------------------------------------
State 3: [25.0, 15.0]
Q-Values:
[-0.9276343   0.69041485 -0.0161992   2.4956448  -0.8472247 ]
--------------------------------------------------
State 4: [10.0, 5.0]
Q-Values:
[-0.39562756  0.36374956 -0.07763044  0.8779759  -0.19091038]
--------------------------------------------------


In [10]:
print("=" * 60)

print("Deep Q-Network Summary")

print("=" * 60)

print(f"State Size  : {state_size}")

print(f"Action Size : {action_size}")

print(f"Device      : {'CUDA' if torch.cuda.is_available() else 'CPU'}")

total_params = sum(p.numel() for p in model.parameters())

print(f"Parameters  : {total_params}")

print("=" * 60)

Deep Q-Network Summary
State Size  : 2
Action Size : 5
Device      : CPU
Parameters  : 6597
